### ISSUE TITLE
Cache not working

### ISSUE THREAD

**Issue by JohannesKaufmann** [apollographql/relay-modern-hello-world#2]
I changed the source code a bit:

```js
// - - - createRelayEnvironment.js - - - //

function fetchQuery(
  operation,
  variables,
  cacheConfig,
  uploadables,
) {
  console.log('fetch ', operation.text, cacheConfig)  // <--
  return fetch('http://api.githunt.com/graphql', {
...

// - - - App.js - - - //

// extracted 'QueryRenderer' into 'Test' Component

class App extends Component {
  constructor (props) {
    super(props)
    this.state = {
      show: true
    }
  }
  render() {
    return (
      <div className="App">
        <h2>Tiny GitHunt</h2>
        {this.state.show && <Test />}
        <button onClick={() => {
          this.setState({show: !this.state.show})
        }}>Test</button>
...

```

Everytime I click the Button to show the list, the fetchQuery function is called again to send the query. Apparently the data is not cached. Do you know why?
Could you expand the example, so that it covers caching as well?

```
# console:
createRelayEnvironment.js:16 fetch  query AppFeedQuery {
  feed(type: NEW, limit: 5) {
    repository {
      owner {
        login
      }
      name
      stargazers_count
    }
    postedBy {
      login
    }
  }
}
 undefined
```

**Comment by stubailo** [comment]
For this example I just followed the docs - so I guess caching is not enabled by default. If you find out how to enable it, please send a PR!

**Comment by JohannesKaufmann** [comment]
I searched everywhere and found nothing. And because I switched to Apollo as soon as the first early version was out, I can't remember what you had to do in relay classic :-(

**Comment by stubailo** [comment]
Yeah, looks like this is just not a feature present in Relay Modern.

**Comment by trongthanh** [comment]
Seems like Relay Modern cache is not publicly documented. But they mention it here: https://github.com/facebook/relay/issues/1687#issuecomment-302931855

**Comment by stubailo** [comment]
Yes, but you can't use it through the `react-relay` `QueryRenderer` API at the moment.

**Comment by stubailo** [comment]
Also, that's not a normalized cache right, it's just a query response cache. So it won't help you load from the cache if you've done a mutation.
